/**
 * Thin fetch wrapper around the API.
 *
 * NEXT_PUBLIC_API_URL points at the Prism mock server (contracts/openapi.yaml)
 * by default — see .env.example and docker-compose.yml — so this app never
 * needs the real Django backend running to be developed against. Point it
 * at a real backend instance once you want live data.
 *
 * Request/response types come from src/lib/api-types.ts, generated by
 * `npm run generate-types` from contracts/openapi.yaml — run
 * `npm run sync-contract` first to pull the latest contract from the
 * backend repo.
 *
 * Per Design Spec Sec 7.2: server state (hackathons, teams, submissions —
 * anything owned by the API) is managed with React Query, not global client
 * state. This client is the single place that knows the base URL and
 * attaches the JWT access token; React Query hooks in each feature/ folder
 * call through it.
 */

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4010";

export async function apiFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${API_URL}/api/v1${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...init?.headers,
    },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new Error(body?.error?.message ?? `Request failed: ${res.status}`);
  }

  return res.json() as Promise<T>;
}
