/**
 * Thin fetch wrapper around the API.
 *
 * NEXT_PUBLIC_API_URL points at the Prism mock server (contracts/openapi.yaml)
 * by default — see .env.example and docker-compose.yml — so this app never
 * needs the real Django backend running to be developed against. Point it
 * at a real backend instance once you want live data.
 *
 * Request/response types come from src/lib/api-types.ts, generated by
 * `npm run generate-types` from contracts/openapi.yaml — run
 * `npm run sync-contract` first to pull the latest contract from the
 * backend repo.
 *
 * Per Design Spec Sec 7.2: server state (hackathons, teams, submissions —
 * anything owned by the API) is managed with React Query, not global client
 * state. This client is the single place that knows the base URL; the two
 * exports below cover the two trust levels every endpoint falls into:
 *
 * - `apiFetch`  — public endpoints (signup, hackathon discovery, ...). No
 *   credential attached.
 * - `authFetch` — anything requiring the signed-in user. Attaches the
 *   in-memory access token (see features/auth/lib/session-store.ts) as a
 *   Bearer header, and on a 401 transparently calls `/api/auth/refresh`
 *   (a same-origin Next.js route that reads the httpOnly refresh cookie)
 *   once and retries the original request. If the refresh itself fails,
 *   the session is cleared and the original 401 propagates so the caller
 *   can redirect to /login.
 */

import {
  clearSession,
  getAccessToken,
  setSession,
} from "@/features/auth/lib/session-store";
import type { SessionResponse } from "./api-types-helpers";

const CLIENT_API_URL =
  process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4010";

const SERVER_API_URL =
  process.env.BACKEND_INTERNAL_URL ?? "http://mock-api:4010";

export class ApiError extends Error {
  status: number;
  fields?: Record<string, string[]>;

  constructor(status: number, message: string, fields?: Record<string, string[]>) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.fields = fields;
  }

  static async fromResponse(res: Response): Promise<ApiError> {
    const body = await res.json().catch(() => null);
    return new ApiError(
      res.status,
      body?.error?.message ?? `Request failed: ${res.status}`,
      body?.error?.fields,
    );
  }
}

async function parseOrThrow<T>(res: Response): Promise<T> {
  if (!res.ok) {
    throw await ApiError.fromResponse(res);
  }
  if (res.status === 204 || res.headers.get("Content-Length") === "0") {
    return undefined as T;
  }
  return res.json() as Promise<T>;
}

export async function apiFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const apiUrl = typeof window === "undefined" ? SERVER_API_URL : CLIENT_API_URL;

  const res = await fetch(`${apiUrl}/api/v1${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...init?.headers,
    },
  });
  return parseOrThrow<T>(res);
}

// Coalesces concurrent 401s into a single refresh call rather than firing
// one per in-flight request.
let refreshInFlight: Promise<boolean> | null = null;

async function silentRefresh(): Promise<boolean> {
  if (!refreshInFlight) {
    refreshInFlight = (async () => {
      try {
        // Same-origin Next.js route (reads the httpOnly refresh cookie) —
        // never the backend/Prism base URL. See auth-client.restoreSession.
        const res = await fetch("/api/auth/refresh", {
          method: "POST",
          credentials: "include",
        });
        if (!res.ok) {
          clearSession();
          return false;
        }
        const data: SessionResponse = await res.json();
        setSession(data.accessToken, data.user);
        return true;
      } catch {
        clearSession();
        return false;
      } finally {
        refreshInFlight = null;
      }
    })();
  }
  return refreshInFlight;
}

export async function authFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const doFetch = () => {
    const token = getAccessToken();
    const apiUrl = typeof window === "undefined" ? SERVER_API_URL : CLIENT_API_URL;
    return fetch(`${apiUrl}/api/v1${path}`, {
      ...init,
      headers: {
        "Content-Type": "application/json",
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
        ...init?.headers,
      },
    });
  };

  let res = await doFetch();

  if (res.status === 401) {
    const refreshed = await silentRefresh();
    if (refreshed) {
      res = await doFetch();
    }
  }

  return parseOrThrow<T>(res);
}
